name: Slack activity
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  send_activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Retrieve recent GitHub activity
        run: node get-github-activity.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send activity to Slack
        uses: rtCamp/action-slack-notify@v2.0
        env:
          SLACK_CHANNEL: <your_slack_channel_id>
          SLACK_MESSAGE: ${{ steps.format_message.outputs.message }}
        with:
          status: ${{ job.status }}
